### ISSUE TITLE
add messages back for verbose option?

### ISSUE THREAD

**Issue by dpprdan** [cboettig/codemeta#12]
While working on #10, I noticed that the verbose option is effectively not used by `guess_provider()` et al. (in order to get rid of the {cli} dependency). 

Should these verbose message be added again with `message()`, also with respect to https://github.com/ropensci/codemetar/issues/319?

**Comment by cboettig** [comment]
right, adding `message()` back with verbose makes sense I think.  

(arguably `verbose` should default to `getOption("verbose", FALSE)` to respect the user's global settings?)
