### ISSUE TITLE
remove fragment from codeRepository URL

### ISSUE THREAD

**Issue by dpprdan** [cboettig/codemeta#13]
The `codeRepository` link contains a fragment (e.g. `#readme`)  if it does so in DESCRIPTION, for example:

``` r
library(codemeta)
write_codemeta(find.package("cli"), file = NULL)$codeRepository
#> [1] "https://github.com/r-lib/cli#readme"
```

Should this be omitted, like `codemetar::write_codemeta` does?

**Comment by cboettig** [comment]
yup, makes sense to trim the fragment identifier
