### ISSUE TITLE
Wrong parsing of meta$ tags on CITATION

### ISSUE THREAD

**Issue by dieghernan** [cboettig/codemeta#7]
Hi! 

Recently I have been developing a package called [**{cffr}**](https://github.com/dieghernan/cffr) (kind of **{codemeta}** but for [CFF format](https://citation-file-format.github.io/)) and I have spent a lot of time working with CITATION files, so some fresh insights on this issue here.

The current implementation on {codemeta} fails to read some CITATION files. This is due to the `meta`  parameter used here:

https://github.com/cboettig/codemeta/blob/1fca0fd22015a2f0935db2c01a6b28bd6def4bd3/R/parse_citation.R#L140-L161

So only the "Encoding" is used. on `utils::readCitationFile(citation_file, meta = meta)`.

 In some other CITATION files the use of `meta$` tags cab be quite extensive, see CITATION of {rmarkdown} where authors, year and title makes use ot the `meta$` approach. These tags are not found since they haven't been provided on the `meta` parameter. See {rmarkdown}:

https://github.com/rstudio/rmarkdown/blob/eaf6efc3fe6d39373ae0cee7ce3a034119bb47f5/inst/CITATION#L3-L19

I have prepared a patch to solve this, based in the approach adopted on {pkgdown} for dealing with this:

https://github.com/r-lib/pkgdown/blob/705ff7c650bb1c7d46d35e72f27ad093689e2f29/R/build-home-citation.R#L6-L29

As this is closely related with #3  , I was thinking on preparing a PR for the fork of  @dpprdan (#4). Let me know what you think of this.

Regards

**Comment by dpprdan** [comment]
Ha, CFF support in R was one reason to look into {codemeta[r]} for me as well. Great to see that you put together a nice package already, @dieghernan, so I don't have to. 😉 
NB: You've probably seen https://github.com/pik-piam/citation, which recently gained a (very basic) `r2cff()` function?

I also noticed that {codemeta} errors when trying to parse {rmarkdown}'s CITATION, but didn't have the time to post it yet. It also only errors with #4 applied. Without it, the CITATION file isn't found by `guess_citation()` when run on the installed, not the source version. 
 
Background: `utils::citation()` supports the use of information from DESCRIPTION via `meta$fieldname`, see “[CITATION files](https://cran.r-project.org/doc/manuals/R-exts.html#CITATION-files)” in WRE. This currently doesn't work with `guess_citation()`.

With {rmarkdown} this leads to an error:

``` r
rmarkdown_path <- find.package("rmarkdown")
codemeta:::guess_citation(rmarkdown_path)
#> Error: $ operator is invalid for atomic vectors
```

`bib` is `[1] "Error in strsplit(meta$URL, \",\") : non-character argument\n"` on my machine.
`strsplit(meta$URL, ',')` stems from line 14 in [{rmarkdown}’s CITATION](https://github.com/rstudio/rmarkdown/blob/eaf6efc3fe6d39373ae0cee7ce3a034119bb47f5/inst/CITATION#L14):

``` r
x <- readLines(file.path(rmarkdown_path, "CITATION"))
x[grepl("meta", x)]
#> [1] "year = sub('.*(2[[:digit:]]{3})-.*', '\\\\1', meta$Date, perl = TRUE)"                             
#> [2] "vers = paste('R package version', meta$Version)"                                                   
#> [3] "auth = format(Filter(function(p) 'aut' %in% p$role, as.person(meta$Author)), c('given', 'family'))"
#> [4] "  title = paste('rmarkdown:', meta$Title),"                                                        
#> [5] "  url = strsplit(meta$URL, ',')[[1]][1],"                                                          
#> [6] "    paste(auth, collapse = ' and '), ' (', year, '). rmarkdown: ', meta$Title, '. ', vers, '.',"
```

`guess_citation()` parses other CITATION files with `meta$`, but silently misses some information.

``` r
# for {cluster} the version number is missing in `$description`
# year is missing altogether
cluster_path <- find.package("cluster")
cm_cit <- codemeta:::guess_citation(cluster_path)
str(cm_cit, max.level = 2)
#>  NULL
cit <- citation("cluster")
cit[[1]]$note
#> [1] "R package version 2.1.2 --- For new features, see the 'Changelog' file (in the package source)"
cit[[1]]$year
#> [1] "2021"
y <- readLines(file.path(cluster_path, "CITATION"))
y[grepl("meta", y)]
#> [1] "year <- sub(\".*(2[[:digit:]]{3})-.*\", \"\\\\1\", meta$Date)"
#> [2] "vers <- paste(\"R package version\", meta$Version)"
```

I agree that a variation of the approach in {pkgdown} should probably fix this. Note how this was already briefly mentioned in the corresponding original {codemetar} issue, cf. https://github.com/ropensci/codemetar/issues/238, https://github.com/ropensci/codemetar/pull/241. But I suppose you've that as well, @dieghernan? 

I also agree that it makes sense to build this off of #4, which I'll try to finish in the next couple of days.

**Comment by dieghernan** [comment]
Hi @dpprdan thanks for your feedback. I opened a PR on your branch (https://github.com/dpprdan/codemeta/pull/1).

FYI I opened a Presubmission Inquiry on rOpenSci for **{cffr}** (see https://github.com/ropensci/software-review/issues/462), mentioned also the **{citation}** package. However I honestly think **{cffr}**  has more features, as complete parsing of the maximum fields, CITATION parsing, a dedicated `cff` class for printing and schema validation using **{jsonvalidate}**.

Regards

**Comment by cboettig** [comment]
Thanks both!  A PR for this here would be most welcome.

`cffr` looks great btw
